=== mattborja/sig3/schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "object",
  "properties": {
    "fingerprint": {
      "type": "string",
      "pattern": "^([A-F0-9]{32}|[A-F0-9]{40}|[A-F0-9]{64})$",
      "description": "Valid GPG fingerprint length (128-bit v3, 160-bit v4, or 256-bit v6), uppercased"
    },
    "label": {
      "type": "string",
      "description": "The label or name associated with the individual or entity, typically matching the name on the GPG key."
    },
    "sources": {
      "type": "array",
      "minItems": 1,
      "items": {
        "type": "object",
        "properties": {
          "type": {
            "type": "string",
            "enum": [
              "url",
              "cache"
            ],
            "description": "The type of source: 'url' for a web URL, 'cache' for a local copy of the public key."
          },
          "uri": {
            "type": "string",
            "description": "The URI of the source, which can be a URL or a copy of the PGP key block with newline characters escaped (see also bin/keyblock-oneline.sh)."
          }
        },
        "required": [
          "type",
          "uri"
        ],
        "additionalProperties": false
      },
      "description": "A list of sources providing the key or related information, which can be a URL or a copy of key data with newline characters escaped (see also bin/keyblock-oneline.sh)."
    },
    "refs": {
      "type": "array",
      "minItems": 1,
      "uniqueItems": true,
      "items": {
        "type": "object",
        "properties": {
          "date": {
            "type": "string",
            "format": "date",
            "description": "The date when the verification or cross-signing took place, in YYYY-MM-DD format."
          },
          "comment": {
            "type": "string",
            "description": "A brief description of what the reference verifies or supports (e.g., project affiliation, key ownership)."
          },
          "artifact": {
            "type": "string",
            "description": "A cryptographic artifact (i.e. clearsigned message) demonstrating possession of a specific key (i.e. signing subkey)"
          },
          "url": {
            "oneOf": [
              {
                "type": "string",
                "format": "uri",
                "description": "A URL pointing to an authoritative source or resource that validates the reference."
              },
              {
                "type": "array",
                "items": {
                  "type": "string",
                  "format": "uri",
                  "description": "A list of related URLs pointing to authoritative sources or resources that validate the reference."
                },
                "description": "A URL (or an array of related URLs) pointing to authoritative sources or resources that validate the reference."
              }
            ]
          },
          "dns": {
            "type": "string",
            "pattern": "^[A-Za-z0-9]+\\._openpgpkey\\.[A-Za-z0-9]([A-Za-z0-9-]{0,61}[A-Za-z0-9])?(\\.[A-Za-z0-9]([A-Za-z0-9-]{0,61}[A-Za-z0-9])?)*$",
            "description": "Valid DNS domain name consisting of one or more labels (separated by dots), with each label containing only letters, numbers, and hyphens, and no label being longer than 63 characters. Provided for OPENPGPKEY DNS resource records (https://datatracker.ietf.org/doc/html/draft-ietf-dane-openpgpkey-06#section-2)."
          },
          "type": {
            "type": "string",
            "enum": [
              "role",
              "user",
              "key",
              "sig1",
              "sig2",
              "sig3",
              "csp"
            ],
            "description": "The type of verification indicated by the evidence provided: project affiliation (role), self-attestation (user), private key use (key), certified by another key holder (sig1, sig2, sig3), certified by a Credential Service Provider (CSP)"
          }
        },
        "required": [
          "date",
          "comment",
          "type"
        ],
        "additionalProperties": false
      },
      "description": "A list of references that provide evidence to support the identity assertion. Each reference must include a date, comment, and type."
    },
    "tags": {
      "type": "array",
      "items": {
        "type": "string",
        "pattern": "[^,]",
        "description": "A list of tags or labels that categorize or identify the individual or entity (e.g., 'OWASP', 'developer')."
      },
      "description": "Tags associated with the identity, which help categorize or identify the individual or entity."
    }
  },
  "required": [
    "fingerprint",
    "label",
    "refs"
  ],
  "additionalProperties": false
}

=== mattborja/sig3/registry/6D18FD63708FCCA079B68CCE026691839355EBCA.json
{
    "fingerprint": "6D18FD63708FCCA079B68CCE026691839355EBCA",
    "label": "Henri Mikkonen",
    "sources": [
      {
        "type": "url",
        "uri": "https://shibboleth.net/downloads/PGP_KEYS"
      }
    ],
    "refs": [
      {
        "date": "2022-04-01",
        "comment": "Self-verified during 2022-04-01 dev call.",
        "url": "https://shibboleth.atlassian.net/wiki/spaces/DEV/pages/2951020545/2022-04-01",
        "type": "user"
      },
      {
        "date": "2022-04-01",
        "comment": "Listed as project lead with other named collaborators in Shibboleth projects: Scott Cantor, Philip Smart, Rod Widdowson, Steven Premeau, Tom Zeller, John W. O'Brien, Daniel Fisher.",
        "url": "https://shibboleth.atlassian.net/jira/projects",
        "type": "role"
      }
    ],
    "tags": [
      "Shibboleth"
    ]
  }

=== mattborja/sig3/registry/DCAA15007BED9DE690CD9523378B845402277962.json
{
    "fingerprint": "DCAA15007BED9DE690CD9523378B845402277962",
    "label": "Scott Cantor",
    "sources": [
      {
        "type": "url",
        "uri": "https://shibboleth.net/downloads/PGP_KEYS"
      }
    ],
    "refs": [
      {
        "date": "2022-04-01",
        "comment": "Cross-signed by 5E6D6EAE16C3DA75450B219C9A804E97D7079C77.",
        "url": "https://pgp.re/pks/lookup?search=0xDCAA15007BED9DE690CD9523378B845402277962&fingerprint=on&op=vindex",
        "type": "user"
      },
      {
        "date": "2022-04-01",
        "comment": "Fingerprint self-verified during 2022-04-01 dev call.",
        "url": "https://shibboleth.atlassian.net/wiki/spaces/DEV/pages/2951020545/2022-04-01",
        "type": "user"
      },
      {
        "date": "2022-04-01",
        "comment": "Podcast (authenticated by same voice on dev call) attesting to acceptance standards, security priorities, and transparency.",
        "url": "https://shibboleth.atlassian.net/wiki/spaces/DEV/pages/2951020545/2022-04-01",
        "type": "role"
      }
    ],
    "tags": [
      "Shibboleth"
    ]
  }

=== mattborja/sig3/registry/A1DB793DC23663E7F91475D82B999FA9CE046B1B.json
{
  "fingerprint": "A1DB793DC23663E7F91475D82B999FA9CE046B1B",
  "label": "Werner Koch (384-bit ECDH key)",
  "sources": [
    {
      "type": "url",
      "uri": "https://gnupg.org/.well-known/openpgpkey/hu/nq6t9teux7edsnwdksswydu4o9i5es3f?l=wk"
    },
    {
      "type": "url",
      "uri": "https://openpgpkey.gnupg.org/.well-known/openpgpkey/gnupg.org/hu/nq6t9teux7edsnwdksswydu4o9i5es3f?l=wk"
    }
  ],
  "refs": [
    {
      "date": "2024-11-27",
      "comment": "User comment by site administrator (werner) indicating key ID",
      "url": "https://dev.gnupg.org/T6561#172087",
      "type": "role"
    },
    {
      "date": "2024-11-27",
      "comment": "User profile and recent activity of named site administrator (werner) with listed project associations: GnuPG project and g10 code CmbH",
      "url": "https://dev.gnupg.org/p/werner/",
      "type": "role"
    },
    {
      "date": "2024-11-27",
      "comment": "Blog post at gnupg.org on ADSK by subject listing full fingerprint of real encryption key used in code samples",
      "url": "https://www.gnupg.org/blog/20230321-adsk.html",
      "type": "role"
    },
    {
      "date": "2024-10-24",
      "comment": "Encrypted email received from wk@gnupg.org (Message-Id: <87jzegnvts.fsf@jacob.g10code.de>) associating the fingerprints of the encryption subkey (2B99 9FA9 CE04 6B1B), the signing subkey (19CC 1C9E 085B 107A), and the primary key (C85C 6311 3AE8 6658 7D0A).",
      "type": "user"
    },
    {
      "date": "2024-11-27",
      "comment": "User comment by site administrator (werner) self-attesting signing subkey (19CC 1C9E 085B 107A) and primary key (C85C 6311 3AE8 6658 7D0A)",
      "url": "https://dev.gnupg.org/T5454#146523",
      "type": "role"
    }
  ],
  "tags": [
    "GnuPG"
  ]
}

=== mattborja/sig3/registry/0675BD19F4FFE3AD0B2D6FEBADA2860895AE3D91.json
{
  "fingerprint": "0675BD19F4FFE3AD0B2D6FEBADA2860895AE3D91",
  "label": "Rocky Linux 9 - Beta Key V1/2022 <releng@rockylinux.org>",
  "sources": [
    {
      "type": "url",
      "uri": "https://dl.rockylinux.org/pub/rocky/RPM-GPG-KEY-rockyofficial"
    }
  ],
  "refs": [
    {
      "date": "2021-02-14",
      "comment": "Listed with release packages as official signing key: RPM-GPG-KEY-Rocky-9-Testing (sha256:8e7fe59a799b38b32112ffa45c5aab83a44144556e1e06ab6ff149a547a1d41e)",
      "url": "https://dl.rockylinux.org/pub/rocky/",
      "type": "role"
    },
    {
      "date": "2024-03-31",
      "comment": "Listed with other Project Keys and instructions for verifying key fingerprints: Rocky Linux 9 (Testing)",
      "url": ["https://github.com/rocky-linux/rockylinux.org/blob/develop/resources/gpg-key-info.md", "https://web.archive.org/web/20240331063950/https://rockylinux.org/keys/", "https://rockylinux.org/resources/gpg-key-info", "https://rockylinux.org/keys"],
      "type": "role"
    },
    {
      "date": "2025-03-17",
      "comment": "Listed in BaseOS source package: rocky-release-9.5-1.2.el9.src.rpm (sha256:975db6f5e89fc5538a5a4b296d66d3fe1fe6a0f1e557dfb95183dec148d8ca79)",
      "url": "https://dl.rockylinux.org/pub/rocky/9/BaseOS/source/tree/Packages/r/rocky-release-9.5-1.2.el9.src.rpm",
      "type": "role"
    }
  ],
  "tags": [
    "Rocky Linux"
  ]
}
